### ISSUE TITLE
Strange wrapping

### ISSUE THREAD

**Issue by victornoel** [thorbenvh8/prettier-java#38]
```java
  @Override
  public SegmentationChart jsonable(
    FactorisedSelection selection
  ) {List<ThingsInformation> dbThingsInformations = new DbThingsInformations(context,
    things,
    new FactorisedFilterCondition(schema,
    selection)).list();
    return new DefaultChart(dbThingsInformations,
    rowLabels,
    rowCumulativePercentThresholds,
    columnLabels,
    columnCumulativePercentThresholds);
  }
```

I suppose this is not normal:
 - the assignment being on the same line as the `{`
 - the one-parameter method being wrapped (I suppose it is a side effect of the first bullet)

I would have expected (on top of #37):
```java
  @Override
  public DefaultChart jsonable(FactorisedSelection selection) {
    List<ThingsInformation> dbThingsInformations = new DbThingsInformations(context,
    things,
    new FactorisedFilterCondition(schema,
    selection)).list();
    return new DefaultChart(dbThingsInformations,
    rowLabels,
    rowCumulativePercentThresholds,
    columnLabels,
    columnCumulativePercentThresholds);
  }
```

**Comment by thorbenvh8** [comment]
maybe give this a shot yourself? :)

**Comment by victornoel** [comment]
@thorbenvh8 honestly, this one is a hell to fix, the node tree doesn't have the right abstractions: we would need to differentiate between block statement and an expression, so that we can have expression inside a statement and variable declaration (instead of field declaration) inside a statement too.

We could then apply wrapping to the statement and not to the expression as it is currently done.

**Comment by thorbenvh8** [comment]
Ok sure I could put that into the parser.

Can you give me two examples when to return what do understand better?

If we have this return block, if we have this return expression. :)

**Comment by victornoel** [comment]
Inside a `BLOCK`, in `node.statements` we should have only `BLOCK_STATEMENT` objects, and inside a `BLOCK_STATEMENT` we should have what is currently present in `BLOCK` (i.e. identifier statement, expression statement and field declaration).

So that the new line rule (that checks if we are in a lambda, etc) currently defined for `EXPRESSION_STATEMENT` can actually be moved to `BLOCK_STATEMENT` and applied to any of the 3 type of block statement.

**Comment by thorbenvh8** [comment]
So you want from:
```json
{
  "type": "BLOCK",
  "statements": [
    {
           "type": "IDENTIFIER_STATEMENT"
    },
    {
           "type": "EXPRESSION_STATEMENT"
    },
    {
           "type": "FIELD_DECLARATION"
     }
  ]
}
```

to:
```json
{
  "type": "BLOCK",
  "statements": [
    {
       "type": "BLOCK_STATEMENT",
       "statement": {
           "type": "IDENTIFIER_STATEMENT"
       }
    },
    {
       "type": "BLOCK_STATEMENT",
       "statement": {
           "type": "EXPRESSION_STATEMENT"
       }
    },
    {
       "type": "BLOCK_STATEMENT",
       "statement": {
           "type": "FIELD_DECLARATION"
       }
    }
  ]
}
```

**Comment by thorbenvh8** [comment]
Did you know you can do path.getParent() (parameter can be a number and that means the parent of level like 1 (default), 2, 3 etc.)
Maybe you can use that?

**Comment by victornoel** [comment]
Let's scratch that, I wonder if the bug is not coming from something simpler:

In the example in the description, the variable declaration is parsed as a `FIELD_DECLARATION`: this doesn't make any sense. Reading the code of chevrotain-java, I can see that a `EXPRESSION_STATEMENT` actually can contains a `LOCAL_VARIABLE_DECLARATION`.
If the variable declaration in the example was inside a node of type `EXPRESSION_STATEMENT`, then the correct printing behaviour would have been applied.

WDYT? Is that a bug in chevrotain-java?

**Comment by thorbenvh8** [comment]
```javascript
void localVariables() { final List<Filter> filterList = new ArrayList<>(); }
```

I get this back from the parser, what would you expect instead?


```javascript
  {
      type: "METHOD_DECLARATION",
      typeType: { type: "VOID" },
      name: { type: "IDENTIFIER", value: "localVariables" },
      parameters: { parameters: [], type: "FORMAL_PARAMETERS" },
      dimensions: [],
      body: {
        type: "BLOCK",
        statements: [
          {
            type: "FIELD_DECLARATION",
            typeType: {
              modifiers: [{ type: "MODIFIER", value: "final" }],
              type: "TYPE_TYPE",
              dimensions: [],
              value: {
                name: { type: "IDENTIFIER", value: "List" },
                type: "CLASS_OR_INTERFACE_TYPE_ELEMENT",
                typeArguments: {
                  type: "TYPE_ARGUMENTS",
                  value: {
                    type: "TYPE_LIST",
                    list: [
                      {
                        type: "TYPE_ARGUMENT",
                        argument: {
                          type: "IDENTIFIER",
                          value: "Filter"
                        },
                        extends: undefined,
                        super: undefined
                      }
                    ]
                  }
                }
              }
            },
            variableDeclarators: {
              type: "VARIABLE_DECLARATORS",
              list: [
                {
                  type: "VARIABLE_DECLARATOR",
                  id: {
                    type: "VARIABLE_DECLARATOR_ID",
                    id: { type: "IDENTIFIER", value: "filterList" },
                    dimensions: []
                  },
                  init: {
                    type: "SIMPLE_CREATOR",
                    name: {
                      elements: [
                        {
                          type: "IDENTIFIER_NAME_ELEMENT",
                          id: {
                            type: "IDENTIFIER",
                            value: "ArrayList"
                          },
                          typeArguments: {
                            type: "TYPE_ARGUMENTS",
                            value: undefined
                          }
                        }
                      ],
                      type: "IDENTIFIER_NAME"
                    },
                    rest: {
                      type: "CLASS_CREATOR_REST",
                      arguments: { list: [], type: "EXPRESSION_LIST" },
                      body: undefined
                    }
                  }
                }
              ]
            },
            followedEmptyLine: false
          }
        ]
      },
      throws: undefined
    }
```

Did you check the visitor code? Maybe there is a bug that I return the wrong ast?

**Comment by victornoel** [comment]
I don't understand how, semantically, a field could be contained in a method block.

I would have expected it to contain an EXPRESSION_STATEMENT, itself containing a LOCAL_VARIABLE_DECLARATION or something like that.

I checked quickly the visitor code of chevrotain-java, but honestly it is not very readable, especially in that place. I'm trying to help understanding where the problem is, but I'm mostly not able to fix it myself because the code is too complex.

**Comment by thorbenvh8** [comment]
Fixed in last release :)

**Comment by victornoel** [comment]
@thorbenvh8 is it really? You only merged my PR in the last release, nothing since then and my PR didn't fix this!

**Comment by thorbenvh8** [comment]
Ups, I released some more stuff but forgot to push the code. On the road right now, so I will push it later :) thanks for the heads up :)

**Comment by victornoel** [comment]
cool, that's great news then :)
